algoritmo "003_funcionarioesalario"
// 3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no final uma mensagem.
var
   nome: Caractere
   salario: Real
inicio
      Escreva("Digite o nome do Funcionário: ")
      leia(nome)
      Escreva("Digite o Salário do Funcionário: R$")
      leia(salario)
      Escreva("O funcionário ", nome, " tem um salário de R$", salario)
fimalgoritmo
